name: flutter_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.8.0-133.0.dev

dependencies:
  flutter:
    sdk: flutter
  wikipedia:
    path: ../wikipedia

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
