name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  http: ^1.3.0
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.0
  wikipedia:
    path: ../wikipedia

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
