name: wikipedia_cli
description: A sample command-line application that fetches articles from Wikipedia.
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.7.0-0

# Add regular dependencies here.
dependencies:
  wikipedia_api:
    path: ../wikipedia_api

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
